# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/cpu_alu_0_0.xci
# IP: The module: 'cpu_alu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_div_gen_0_0/alu_div_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_div_gen_0_0 || ORIG_REF_NAME==alu_div_gen_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_mult_gen_0_0/alu_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_mult_gen_0_0 || ORIG_REF_NAME==alu_mult_gen_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_c_addsub_0_0/alu_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_c_addsub_0_0 || ORIG_REF_NAME==alu_c_addsub_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_c_addsub_1_0/alu_c_addsub_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_c_addsub_1_0 || ORIG_REF_NAME==alu_c_addsub_1_0} -quiet] -quiet

# XDC: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_alu_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/cpu_alu_0_0.xci
# IP: The module: 'cpu_alu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_div_gen_0_0/alu_div_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_div_gen_0_0 || ORIG_REF_NAME==alu_div_gen_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_mult_gen_0_0/alu_mult_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_mult_gen_0_0 || ORIG_REF_NAME==alu_mult_gen_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_c_addsub_0_0/alu_c_addsub_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_c_addsub_0_0 || ORIG_REF_NAME==alu_c_addsub_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_c_addsub_1_0/alu_c_addsub_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_c_addsub_1_0 || ORIG_REF_NAME==alu_c_addsub_1_0} -quiet] -quiet

# XDC: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/src/alu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_alu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
