# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/top.xdc

# Block Designs: C:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/cpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu || ORIG_REF_NAME==cpu} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_debounce_0_0/cpu_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_debounce_0_0 || ORIG_REF_NAME==cpu_debounce_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_isa_decoder_0_0/cpu_isa_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_isa_decoder_0_0 || ORIG_REF_NAME==cpu_isa_decoder_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_ssd_0_0/cpu_ssd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_ssd_0_0 || ORIG_REF_NAME==cpu_ssd_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_register_0_0/cpu_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_register_0_0 || ORIG_REF_NAME==cpu_register_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_alu_0_0/cpu_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_alu_0_0 || ORIG_REF_NAME==cpu_alu_0_0} -quiet] -quiet

# IP: c:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/ip/cpu_mux_0_2/cpu_mux_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_mux_0_2 || ORIG_REF_NAME==cpu_mux_0_2} -quiet] -quiet

# XDC: C:/Users/justi/OneDrive/Desktop/Spring 2021/CMPE415/HW/Justin_Loi_HW4/cpu/cpu_ooc.xdc
